<?php

namespace GlpiPlugin\Glpistyle;

use Glpi\RichText\RichText;
use Notification;
use Notification_NotificationTemplate;
use QueuedNotification;

/**
 * Removes from the e-mails sent by GLPI what NotificationTemplate appends to
 * every one of them: the "-- <signature>" block (Setup > Notifications >
 * Email followups configuration, or the entity's) and the line
 * "Automatically generated by GLPI".
 *
 * Done on the queue entry (pre_item_add of QueuedNotification), where every
 * e-mail passes before being sent - the core and every plugin's.
 */
final class Mail
{
    public static function isActive(array $config): bool
    {
        return (int) $config['mail_hide_signature'] === 1 || (int) $config['mail_hide_footer'] === 1;
    }

    public static function cleanQueued(QueuedNotification $item): void
    {
        if (!is_array($item->input) || ($item->input['mode'] ?? '') !== Notification_NotificationTemplate::MODE_MAIL) {
            return;
        }
        $config = Config::get();
        $signature = (int) $config['mail_hide_signature'] === 1
            ? trim((string) Notification::getMailingSignature((int) ($item->input['entities_id'] ?? 0)))
            : '';
        $footer = (int) $config['mail_hide_footer'] === 1;

        if (isset($item->input['body_html']) && is_string($item->input['body_html'])) {
            $item->input['body_html'] = self::cleanHtml($item->input['body_html'], $signature, $footer);
        }
        if (isset($item->input['body_text']) && is_string($item->input['body_text'])) {
            $item->input['body_text'] = self::cleanText($item->input['body_text'], $signature, $footer);
        }
    }

    /** Same layout as NotificationTemplate::getTemplateByLanguage() */
    public static function cleanHtml(string $html, string $signature, bool $footer): string
    {
        global $CFG_GLPI;

        if ($footer) {
            // "<br>Automatically generated by GLPI<br><br>\n" right before
            // the (usually empty) target footer and </body>; translated in
            // the recipient's language, so matched by the app name
            $app = preg_quote(htmlescape((string) $CFG_GLPI['app_name']), '/');
            $html = preg_replace('/<br>[^<]*' . $app . '[^<]*<br><br>\n(?=(?:.*\n<br><br>)?\n<\/body><\/html>\s*$)/s', '', $html, 1) ?? $html;
        }
        if ($signature !== '') {
            $block = "<br><br>-- \n<br>" . RichText::getSafeHtml($signature);
            $pos = strrpos($html, $block);
            if ($pos !== false) {
                $html = substr_replace($html, '', $pos, strlen($block));
            }
        }
        return $html;
    }

    public static function cleanText(string $text, string $signature, bool $footer): string
    {
        global $CFG_GLPI;

        if ($footer) {
            $app = preg_quote((string) $CFG_GLPI['app_name'], '/');
            $text = preg_replace('/\n[^\n]*' . $app . '[^\n]*\n\n(?=[^\n]*$)/', "\n", $text, 1) ?? $text;
        }
        if ($signature !== '') {
            $block = "\n\n-- \n" . RichText::getTextFromHtml($signature, false, false);
            $pos = strrpos($text, $block);
            if ($pos !== false) {
                $text = substr_replace($text, '', $pos, strlen($block));
            }
        }
        return rtrim($text) . "\n";
    }
}
